# Generated by Django 5.2 on 2025-04-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("culture", models.JSONField()),
                ("images", models.JSONField()),
                ("language", models.CharField(max_length=100)),
                ("traditions", models.TextField()),
                ("audio", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
